name: bio-R
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.3
  - biopython=1.76
  - jupyter=1.0.0
  - numpy=1.18.1
  - pandas=0.25.2
  - scipy=1.2.0
  - r-essentials=3.6.0
  - r-ncvreg=3.11_1
  - pip=20.0.2
  - pip:
    - pycasso==0.1.2.2
